name: "APéRé"
description: Notes on code, diy, surf, mountain and more.
meta_description: "Notes on code, diy, surf, mountain and more."

markdown: kramdown
highlighter: rouge
logo: true
paginate: 15
baseurl: ""
domain_name: "blog.apere.me"
google_analytics: "UA-XXXXXXXX-X"
plugins: [
    jekyll-paginate,
    github-pages
    ]

# Details for the RSS feed generator
url: ""
author: "apere"

# Disqus config
disqus-shortname: ""
