name: "APéRé"
description: Notes on code, diy, surf, mountain and more.
meta_description: "Notes on code, diy, surf, mountain and more."

destination: "../www"
baseurl: ""

markdown: kramdown
highlighter: rouge
logo: true
paginate: 15
domain_name: "blog.apere.me"
google_analytics: "UA-XXXXXXXX-X"
plugins:
  [
    jekyll-paginate,
    github-pages,
    jekyll-org
  ]

# Details for the RSS feed generator
url: ""
author: "apere"

# Disqus config
disqus-shortname: ""
